<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payslip</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
    <style>

        body {
            font-family: 'Poppins', sans-serif;
            font-size: 13px;
            margin: 20px;
            color: #333;
        }

        .company {
            text-align: center;
            font-size: 24px;
            font-weight: 500;
            color: #2c5282;
            margin-bottom: 5px;
        }

        .title {
            text-align: center;
            font-size: 18px;
            margin-bottom: 20px;
            color: #4a5568;
        }

        .info {
            margin-bottom: 20px;
            line-height: 1.6;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #edf2f7;
            padding: 10px;
            text-align: left;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
        }

        .net {
            text-align: center;
            font-size: 18px;
            font-weight: 500;
            color: #2d3748;
            padding: 15px;
            background-color: #f7fafc;
            border-radius: 5px;
            margin: 20px 0;
        }

        .footer {
            margin-top: 20px;
            padding-top: 15px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #718096;
        }

    </style>
</head>
<body>

<div class="company">N:Company</div>
<div class="title">Salary Payslip</div>

<div class="info">
    <strong>Employee:</strong> {{ $payroll->employee->first_name }} {{ $payroll->employee->last_name }}<br>
    <strong>Position:</strong> {{ ucwords(str_replace('_', ' ', $payroll->employee->latestContract->job_title->value)) }}<br>
    <strong>Month:</strong> {{ $payroll->month_year->format('M Y') }}<br>
    @if($payroll->paid_date)
        <strong>Pay Date:</strong> {{ $payroll->paid_date }}<br>
    @endif
</div>

<table>
    <tr><th colspan="2">Earnings</th></tr>
    <tr><td>Basic Salary</td><td align="right">{{ number_format($payroll->basic_salary, 2) }}</td></tr>
    <tr><td>Overtime</td><td align="right">{{ number_format($payroll->overtime_pay, 2) }}</td></tr>
    <tr><td>Bonus</td><td align="right">{{ number_format($payroll->bonus, 2) }}</td></tr>
</table>

<table>
    <tr><th colspan="2">Deductions</th></tr>
    <tr><td>Total Deductions</td><td align="right">{{ number_format($payroll->deductions, 2) }}</td></tr>
</table>

<div class="net">Net Salary: {{ number_format($payroll->net_salary, 2) }}</div>

<div class="footer">
    Status: {{ ucfirst($payroll->payment_status->value) }}<br>
    Generated by: {{ optional($payroll->generator)->name ?? 'System' }}
</div>

</body>
</html>
