<?php

namespace App\Exports;

use App\Models\Payroll;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use PhpOffice\PhpSpreadsheet\Shared\Date;

class PayrollsExport implements FromQuery, WithHeadings, WithMapping
{
    /**
     * @return \Illuminate\Support\Collection
     */
    public function query()
    {
        return Payroll::query()->with(['employee', 'generator']);
    }

    public function map($payroll): array
    {
        return [
            $payroll->employee->first_name . ' ' . $payroll->employee->last_name,
            Date::dateTimeToExcel($payroll->month_year,),
            $payroll->basic_salary,
            $payroll->overtime_pay,
            $payroll->bonus,
            $payroll->deductions,
            $payroll->net_salary,
            $payroll->payment_status->value,
            $payroll->paid_date ? Date::dateTimeToExcel($payroll->paid_date) : 'N/A',
            $payroll->generator->name,
        ];
    }

    public function headings(): array
    {
        return [
            'Employee',
            'Month Year',
            'Basic Salary',
            'Overtime Salary',
            'Bonus Salary',
            'Deduction Salary',
            'Net Salary',
            'Payroll Status',
            'Pay Date',
            'Generated By',
        ];
    }
}
