<?php

namespace App\Exports;

use App\Models\Payroll;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class PayrollsExport implements FromCollection, WithHeadings
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return Payroll::all();
    }
    public function headings(): array
    {
        return [
            'Payroll ID',
            'Employee ID',
            'Month Year',
            'Basic Salary',
            'Overtime Salary',
            'Bonus Salary',
            'Deduction Salary',
            'Net Salary',
            'Payroll Status',
            'Pay Date',
            'Generated By',
            'Created At',
            'Updated At'
        ];
    }
}
